### ISSUE TITLE
Any ETA on when these proceedings will be on the Arxiv?

### ISSUE THREAD

**Issue by springcoil** [euroscipy/euroscipy_proceedings#54]
Hi all, 
Any update on when these proceedings will be on the Arxiv?

**Comment by springcoil** [comment]
@NelleV or @cournape may be able to answer this question...

**Comment by mnowotka** [comment]
Guys? My team spent some time preparing our paper and I'd like it to be published.

**Comment by Stewori** [comment]
The future-work-section of my paper already starts outdating... I wonder whether I should file another PR to update some info there...

**Comment by springcoil** [comment]
Hi all, :+1: on the updating I spent some time preparing that work too. The
peer review is done already.

On Wed, Jun 1, 2016 at 12:47 PM, Stefan Richthofer <notifications@github.com
> wrote:

> The future-work-section of my paper already starts outdating... I wonder
> whether I should file another PR to update some info there...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/euroscipy/euroscipy_proceedings/issues/54#issuecomment-222969069>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA8DiPs5bOT_U6hlxB4QA8xwrWQRrb_mks5qHXFHgaJpZM4H0uDr>
> .
>



-- 
Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by NelleV** [comment]
Hello,

I'm sorry it is taking so long. I've got a couple of things to fix before publishing those on arxiv.

Thanks,
Nelle

**Comment by Stewori** [comment]
@NelleV 
while my earlier post about another update of the paper was partly a joke I now have significant update I'd like to include if possible. This would mean one more PR, updating versioning, date and compatibility information in the Demo and future work section and the web-dates in the references.
Given your recent activity here, is there already a foreseeable release date now?
I'd appreciate if you could give an explicit okay for such a late update before I start this work. I think I could get it done within some hours, 12 at most, but wouldn't want to start this work if it's not allowed so late.

Thanks in advance!

**Comment by NelleV** [comment]
I've litterally just submitted the articles on arxiv. They are being processed right now.
I think I can still update the articles, as they are still being processed, but this is just a hypothesis.

**Comment by springcoil** [comment]
Cool I want to see the arxiv

**Comment by Stewori** [comment]
@NelleV Taking a look at my 2013 euroscipy proceeding article http://arxiv.org/abs/1404.6390v2 it lists two versions (always wondered why) v1 and v2. Could/would you upload a potential update as increased version? (This way the updated information would even be transparent on archiv.) (Sorry for bothering you; if it's too complicated I'm also fine.)

**Comment by NelleV** [comment]
I have moderation problems and all the submissions were removed by the moderators just now, so… go for it!

**Comment by Stewori** [comment]
Alright :) I'm gonna hack it over night and will give note as soon as possible. Thanks!

**Comment by Stewori** [comment]
@NelleV So, I am done. Hope, everything still fits.

**Comment by NelleV** [comment]
The papers are all out, and I have submitted the index this afternoon. I am thus closing this issue.

Thanks everyone for your patience !
